# Generated by Django 5.1.1 on 2024-10-12 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviesdb',
            old_name='mainActor',
            new_name='main_actor',
        ),
    ]
