# Generated by Django 5.1.1 on 2024-10-26 21:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_moviesdb_main_actor_alter_moviesdb_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesdb',
            name='main_actor',
            field=models.CharField(default='Din Viesel', max_length=20, validators=[django.core.validators.RegexValidator(message='Please only use Letters! No Numbers or Symbols allowed.', regex='^[a-zA-Z]$')]),
        ),
    ]
