# Generated by Django 5.1.1 on 2024-10-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_alter_moviesdb_main_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesdb',
            name='main_actor',
            field=models.CharField(default='Din Viesel', max_length=20),
        ),
    ]
