# Generated by Django 5.1.1 on 2024-10-28 03:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_alter_moviesdb_main_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesdb',
            name='main_actor',
            field=models.CharField(default='Din Viesel', max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', 'Please only use letters and spaces for the name of the actor!')]),
        ),
    ]
