# Generated by Django 5.1.1 on 2024-10-28 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_alter_moviesdb_main_actor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviesdb',
            name='main_actor',
        ),
    ]
