# Generated by Django 5.1.1 on 2024-10-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_remove_moviesdb_main_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesdb',
            name='main_actor',
            field=models.CharField(default='Din Viesel', max_length=20),
        ),
    ]
