# Generated by Django 5.1.1 on 2024-10-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_moviesdb_main_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesdb',
            name='name',
            field=models.CharField(default='Slow and Relaxed', error_messages={'required': 'A movie with that name was already found! Cannot create it.'}, max_length=50, unique=True),
        ),
    ]
