# Generated by Django 5.1.1 on 2024-10-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_alter_moviesdb_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesdb',
            name='main_actor',
            field=models.CharField(default='din viesel', max_length=20),
        ),
        migrations.AlterField(
            model_name='moviesdb',
            name='name',
            field=models.CharField(default='Slow and Relaxed', error_messages={'unique': 'A movie with that name was already found! Cannot create it.'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='moviesdb',
            name='plot',
            field=models.CharField(default='2 guys go really slow in their sports cars, do not add a "." at the end', max_length=100),
        ),
    ]
