# Generated by Django 5.1.1 on 2024-10-28 23:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_alter_moviesdb_main_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesdb',
            name='main_actor',
            field=models.CharField(default='din viesel', max_length=20, validators=[django.core.validators.RegexValidator(code='invalid value', message='Enter letters only.', regex='^[a-zA-Z ]+$')]),
        ),
    ]
