# Generated by Django 5.1.1 on 2024-11-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_alter_moviesdb_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesdb',
            name='moviePic',
            field=models.ImageField(blank=True, null=True, upload_to='moviepics'),
        ),
    ]
