# Generated by Django 5.1.1 on 2024-10-28 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_extras_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='extras',
            name='birth_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='extras',
            name='genre',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('TransMasc', 'Trans Masculine'), ('TransFem', 'Trans Femenine'), ('NonBi', 'Non Binary'), ('N/A', 'Prefer to not answer')], default='N/A', max_length=50),
        ),
    ]
