# Generated by Django 5.1.1 on 2024-10-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_extras_birth_date_extras_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extras',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extras',
            name='genre',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('TransMasc', 'Trans Masculine'), ('TransFem', 'Trans Femenine'), ('NonBi', 'Non Binary'), ('N/A', 'Prefer to not answer')], max_length=50, null=True),
        ),
    ]
